// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package apprpc

import (
	"context"

	"storm-server/app/sys/cmd/rpc/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq               = sysClient.AddAppReq
	AddAppResp              = sysClient.AddAppResp
	AddDepartmentReq        = sysClient.AddDepartmentReq
	AddDepartmentResp       = sysClient.AddDepartmentResp
	AddPermissionReq        = sysClient.AddPermissionReq
	AddPermissionResp       = sysClient.AddPermissionResp
	AddRoleReq              = sysClient.AddRoleReq
	AddRoleResp             = sysClient.AddRoleResp
	AppInfoReq              = sysClient.AppInfoReq
	AppInfoResp             = sysClient.AppInfoResp
	DeleteAppReq            = sysClient.DeleteAppReq
	DeleteAppResp           = sysClient.DeleteAppResp
	DeleteDepartmentReq     = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp    = sysClient.DeleteDepartmentResp
	DeletePermissionReq     = sysClient.DeletePermissionReq
	DeletePermissionResp    = sysClient.DeletePermissionResp
	DeleteRoleReq           = sysClient.DeleteRoleReq
	DeleteRoleResp          = sysClient.DeleteRoleResp
	DeleteUserReq           = sysClient.DeleteUserReq
	DeleteUserResp          = sysClient.DeleteUserResp
	DepartmentInfoReq       = sysClient.DepartmentInfoReq
	DepartmentInfoResp      = sysClient.DepartmentInfoResp
	GetRolePermissionReq    = sysClient.GetRolePermissionReq
	GetRolePermissionResp   = sysClient.GetRolePermissionResp
	GetUerRoleReq           = sysClient.GetUerRoleReq
	GetUerRoleResp          = sysClient.GetUerRoleResp
	GrantRolePermissionReq  = sysClient.GrantRolePermissionReq
	GrantRolePermissionResp = sysClient.GrantRolePermissionResp
	GrantRoleReq            = sysClient.GrantRoleReq
	GrantRoleResp           = sysClient.GrantRoleResp
	ListAppReq              = sysClient.ListAppReq
	ListAppResp             = sysClient.ListAppResp
	ListDepartmentReq       = sysClient.ListDepartmentReq
	ListDepartmentResp      = sysClient.ListDepartmentResp
	ListPermissionReq       = sysClient.ListPermissionReq
	ListPermissionResp      = sysClient.ListPermissionResp
	ListRoleReq             = sysClient.ListRoleReq
	ListRoleResp            = sysClient.ListRoleResp
	LoginReq                = sysClient.LoginReq
	LoginResp               = sysClient.LoginResp
	PermissionInfoReq       = sysClient.PermissionInfoReq
	PermissionInfoResp      = sysClient.PermissionInfoResp
	RoleInfoReq             = sysClient.RoleInfoReq
	RoleInfoResp            = sysClient.RoleInfoResp
	UerInfoReq              = sysClient.UerInfoReq
	UpdateAppReq            = sysClient.UpdateAppReq
	UpdateAppResp           = sysClient.UpdateAppResp
	UpdateDepartmentReq     = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp    = sysClient.UpdateDepartmentResp
	UpdatePermissionReq     = sysClient.UpdatePermissionReq
	UpdatePermissionResp    = sysClient.UpdatePermissionResp
	UpdateRoleReq           = sysClient.UpdateRoleReq
	UpdateRoleResp          = sysClient.UpdateRoleResp
	UpdateUserReq           = sysClient.UpdateUserReq
	UpdateUserResp          = sysClient.UpdateUserResp
	UserInfo                = sysClient.UserInfo
	UserInfoResp            = sysClient.UserInfoResp
	UserListReq             = sysClient.UserListReq
	UserListResp            = sysClient.UserListResp

	AppRpc interface {
		AppAdd(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AddAppResp, error)
		AppInfo(ctx context.Context, in *AppInfoReq, opts ...grpc.CallOption) (*AppInfoResp, error)
		AppList(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error)
		AppUpdate(ctx context.Context, in *UpdateAppReq, opts ...grpc.CallOption) (*UpdateAppResp, error)
		AppDelete(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error)
	}

	defaultAppRpc struct {
		cli zrpc.Client
	}
)

func NewAppRpc(cli zrpc.Client) AppRpc {
	return &defaultAppRpc{
		cli: cli,
	}
}

func (m *defaultAppRpc) AppAdd(ctx context.Context, in *AddAppReq, opts ...grpc.CallOption) (*AddAppResp, error) {
	client := sysClient.NewAppRpcClient(m.cli.Conn())
	return client.AppAdd(ctx, in, opts...)
}

func (m *defaultAppRpc) AppInfo(ctx context.Context, in *AppInfoReq, opts ...grpc.CallOption) (*AppInfoResp, error) {
	client := sysClient.NewAppRpcClient(m.cli.Conn())
	return client.AppInfo(ctx, in, opts...)
}

func (m *defaultAppRpc) AppList(ctx context.Context, in *ListAppReq, opts ...grpc.CallOption) (*ListAppResp, error) {
	client := sysClient.NewAppRpcClient(m.cli.Conn())
	return client.AppList(ctx, in, opts...)
}

func (m *defaultAppRpc) AppUpdate(ctx context.Context, in *UpdateAppReq, opts ...grpc.CallOption) (*UpdateAppResp, error) {
	client := sysClient.NewAppRpcClient(m.cli.Conn())
	return client.AppUpdate(ctx, in, opts...)
}

func (m *defaultAppRpc) AppDelete(ctx context.Context, in *DeleteAppReq, opts ...grpc.CallOption) (*DeleteAppResp, error) {
	client := sysClient.NewAppRpcClient(m.cli.Conn())
	return client.AppDelete(ctx, in, opts...)
}
