// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package departmentrpc

import (
	"context"

	"storm-server/app/sys/cmd/rpc/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddClientReq            = sysClient.AddClientReq
	AddClientResp           = sysClient.AddClientResp
	AddDepartmentReq        = sysClient.AddDepartmentReq
	AddDepartmentResp       = sysClient.AddDepartmentResp
	AddPermissionReq        = sysClient.AddPermissionReq
	AddPermissionResp       = sysClient.AddPermissionResp
	AddRoleReq              = sysClient.AddRoleReq
	AddRoleResp             = sysClient.AddRoleResp
	ClientInfoReq           = sysClient.ClientInfoReq
	ClientInfoResp          = sysClient.ClientInfoResp
	DeleteClientReq         = sysClient.DeleteClientReq
	DeleteClientResp        = sysClient.DeleteClientResp
	DeleteDepartmentReq     = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp    = sysClient.DeleteDepartmentResp
	DeletePermissionReq     = sysClient.DeletePermissionReq
	DeletePermissionResp    = sysClient.DeletePermissionResp
	DeleteRoleReq           = sysClient.DeleteRoleReq
	DeleteRoleResp          = sysClient.DeleteRoleResp
	DeleteUserReq           = sysClient.DeleteUserReq
	DeleteUserResp          = sysClient.DeleteUserResp
	DepartmentInfoReq       = sysClient.DepartmentInfoReq
	DepartmentInfoResp      = sysClient.DepartmentInfoResp
	GetRolePermissionReq    = sysClient.GetRolePermissionReq
	GetRolePermissionResp   = sysClient.GetRolePermissionResp
	GetUerRoleReq           = sysClient.GetUerRoleReq
	GetUerRoleResp          = sysClient.GetUerRoleResp
	GrantRolePermissionReq  = sysClient.GrantRolePermissionReq
	GrantRolePermissionResp = sysClient.GrantRolePermissionResp
	GrantRoleReq            = sysClient.GrantRoleReq
	GrantRoleResp           = sysClient.GrantRoleResp
	ListClientReq           = sysClient.ListClientReq
	ListClientResp          = sysClient.ListClientResp
	ListDepartmentReq       = sysClient.ListDepartmentReq
	ListDepartmentResp      = sysClient.ListDepartmentResp
	ListPermissionReq       = sysClient.ListPermissionReq
	ListPermissionResp      = sysClient.ListPermissionResp
	ListRoleReq             = sysClient.ListRoleReq
	ListRoleResp            = sysClient.ListRoleResp
	LoginReq                = sysClient.LoginReq
	LoginResp               = sysClient.LoginResp
	PermissionInfoReq       = sysClient.PermissionInfoReq
	PermissionInfoResp      = sysClient.PermissionInfoResp
	RoleInfoReq             = sysClient.RoleInfoReq
	RoleInfoResp            = sysClient.RoleInfoResp
	UerInfoReq              = sysClient.UerInfoReq
	UpdateClientReq         = sysClient.UpdateClientReq
	UpdateClientResp        = sysClient.UpdateClientResp
	UpdateDepartmentReq     = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp    = sysClient.UpdateDepartmentResp
	UpdatePermissionReq     = sysClient.UpdatePermissionReq
	UpdatePermissionResp    = sysClient.UpdatePermissionResp
	UpdateRoleReq           = sysClient.UpdateRoleReq
	UpdateRoleResp          = sysClient.UpdateRoleResp
	UpdateUserReq           = sysClient.UpdateUserReq
	UpdateUserResp          = sysClient.UpdateUserResp
	UserInfo                = sysClient.UserInfo
	UserInfoResp            = sysClient.UserInfoResp
	UserListReq             = sysClient.UserListReq
	UserListResp            = sysClient.UserListResp

	DepartmentRpc interface {
		DepartmentAdd(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error)
		DepartmentInfo(ctx context.Context, in *DepartmentInfoReq, opts ...grpc.CallOption) (*DepartmentInfoResp, error)
		DepartmentList(ctx context.Context, in *ListDepartmentReq, opts ...grpc.CallOption) (*ListDepartmentResp, error)
		DepartmentUpdate(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error)
		DepartmentDelete(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error)
	}

	defaultDepartmentRpc struct {
		cli zrpc.Client
	}
)

func NewDepartmentRpc(cli zrpc.Client) DepartmentRpc {
	return &defaultDepartmentRpc{
		cli: cli,
	}
}

func (m *defaultDepartmentRpc) DepartmentAdd(ctx context.Context, in *AddDepartmentReq, opts ...grpc.CallOption) (*AddDepartmentResp, error) {
	client := sysClient.NewDepartmentRpcClient(m.cli.Conn())
	return client.DepartmentAdd(ctx, in, opts...)
}

func (m *defaultDepartmentRpc) DepartmentInfo(ctx context.Context, in *DepartmentInfoReq, opts ...grpc.CallOption) (*DepartmentInfoResp, error) {
	client := sysClient.NewDepartmentRpcClient(m.cli.Conn())
	return client.DepartmentInfo(ctx, in, opts...)
}

func (m *defaultDepartmentRpc) DepartmentList(ctx context.Context, in *ListDepartmentReq, opts ...grpc.CallOption) (*ListDepartmentResp, error) {
	client := sysClient.NewDepartmentRpcClient(m.cli.Conn())
	return client.DepartmentList(ctx, in, opts...)
}

func (m *defaultDepartmentRpc) DepartmentUpdate(ctx context.Context, in *UpdateDepartmentReq, opts ...grpc.CallOption) (*UpdateDepartmentResp, error) {
	client := sysClient.NewDepartmentRpcClient(m.cli.Conn())
	return client.DepartmentUpdate(ctx, in, opts...)
}

func (m *defaultDepartmentRpc) DepartmentDelete(ctx context.Context, in *DeleteDepartmentReq, opts ...grpc.CallOption) (*DeleteDepartmentResp, error) {
	client := sysClient.NewDepartmentRpcClient(m.cli.Conn())
	return client.DepartmentDelete(ctx, in, opts...)
}
