// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package permissionrpc

import (
	"context"

	"storm-server/app/sys/cmd/rpc/sysClient"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddAppReq               = sysClient.AddAppReq
	AddAppResp              = sysClient.AddAppResp
	AddDepartmentReq        = sysClient.AddDepartmentReq
	AddDepartmentResp       = sysClient.AddDepartmentResp
	AddPermissionReq        = sysClient.AddPermissionReq
	AddPermissionResp       = sysClient.AddPermissionResp
	AddRoleReq              = sysClient.AddRoleReq
	AddRoleResp             = sysClient.AddRoleResp
	AppInfoReq              = sysClient.AppInfoReq
	AppInfoResp             = sysClient.AppInfoResp
	DeleteAppReq            = sysClient.DeleteAppReq
	DeleteAppResp           = sysClient.DeleteAppResp
	DeleteDepartmentReq     = sysClient.DeleteDepartmentReq
	DeleteDepartmentResp    = sysClient.DeleteDepartmentResp
	DeletePermissionReq     = sysClient.DeletePermissionReq
	DeletePermissionResp    = sysClient.DeletePermissionResp
	DeleteRoleReq           = sysClient.DeleteRoleReq
	DeleteRoleResp          = sysClient.DeleteRoleResp
	DeleteUserReq           = sysClient.DeleteUserReq
	DeleteUserResp          = sysClient.DeleteUserResp
	DepartmentInfoReq       = sysClient.DepartmentInfoReq
	DepartmentInfoResp      = sysClient.DepartmentInfoResp
	GetRolePermissionReq    = sysClient.GetRolePermissionReq
	GetRolePermissionResp   = sysClient.GetRolePermissionResp
	GetUerRoleReq           = sysClient.GetUerRoleReq
	GetUerRoleResp          = sysClient.GetUerRoleResp
	GrantRolePermissionReq  = sysClient.GrantRolePermissionReq
	GrantRolePermissionResp = sysClient.GrantRolePermissionResp
	GrantRoleReq            = sysClient.GrantRoleReq
	GrantRoleResp           = sysClient.GrantRoleResp
	ListAppReq              = sysClient.ListAppReq
	ListAppResp             = sysClient.ListAppResp
	ListDepartmentReq       = sysClient.ListDepartmentReq
	ListDepartmentResp      = sysClient.ListDepartmentResp
	ListPermissionReq       = sysClient.ListPermissionReq
	ListPermissionResp      = sysClient.ListPermissionResp
	ListRoleReq             = sysClient.ListRoleReq
	ListRoleResp            = sysClient.ListRoleResp
	LoginReq                = sysClient.LoginReq
	LoginResp               = sysClient.LoginResp
	PermissionInfoReq       = sysClient.PermissionInfoReq
	PermissionInfoResp      = sysClient.PermissionInfoResp
	RoleInfoReq             = sysClient.RoleInfoReq
	RoleInfoResp            = sysClient.RoleInfoResp
	UerInfoReq              = sysClient.UerInfoReq
	UpdateAppReq            = sysClient.UpdateAppReq
	UpdateAppResp           = sysClient.UpdateAppResp
	UpdateDepartmentReq     = sysClient.UpdateDepartmentReq
	UpdateDepartmentResp    = sysClient.UpdateDepartmentResp
	UpdatePermissionReq     = sysClient.UpdatePermissionReq
	UpdatePermissionResp    = sysClient.UpdatePermissionResp
	UpdateRoleReq           = sysClient.UpdateRoleReq
	UpdateRoleResp          = sysClient.UpdateRoleResp
	UpdateUserReq           = sysClient.UpdateUserReq
	UpdateUserResp          = sysClient.UpdateUserResp
	UserInfo                = sysClient.UserInfo
	UserInfoResp            = sysClient.UserInfoResp
	UserListReq             = sysClient.UserListReq
	UserListResp            = sysClient.UserListResp

	PermissionRpc interface {
		PermissionAdd(ctx context.Context, in *AddPermissionReq, opts ...grpc.CallOption) (*AddPermissionResp, error)
		PermissionInfo(ctx context.Context, in *PermissionInfoReq, opts ...grpc.CallOption) (*PermissionInfoResp, error)
		PermissionList(ctx context.Context, in *ListPermissionReq, opts ...grpc.CallOption) (*ListPermissionResp, error)
		PermissionUpdate(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*UpdatePermissionResp, error)
		PermissionDelete(ctx context.Context, in *DeletePermissionReq, opts ...grpc.CallOption) (*DeletePermissionResp, error)
	}

	defaultPermissionRpc struct {
		cli zrpc.Client
	}
)

func NewPermissionRpc(cli zrpc.Client) PermissionRpc {
	return &defaultPermissionRpc{
		cli: cli,
	}
}

func (m *defaultPermissionRpc) PermissionAdd(ctx context.Context, in *AddPermissionReq, opts ...grpc.CallOption) (*AddPermissionResp, error) {
	client := sysClient.NewPermissionRpcClient(m.cli.Conn())
	return client.PermissionAdd(ctx, in, opts...)
}

func (m *defaultPermissionRpc) PermissionInfo(ctx context.Context, in *PermissionInfoReq, opts ...grpc.CallOption) (*PermissionInfoResp, error) {
	client := sysClient.NewPermissionRpcClient(m.cli.Conn())
	return client.PermissionInfo(ctx, in, opts...)
}

func (m *defaultPermissionRpc) PermissionList(ctx context.Context, in *ListPermissionReq, opts ...grpc.CallOption) (*ListPermissionResp, error) {
	client := sysClient.NewPermissionRpcClient(m.cli.Conn())
	return client.PermissionList(ctx, in, opts...)
}

func (m *defaultPermissionRpc) PermissionUpdate(ctx context.Context, in *UpdatePermissionReq, opts ...grpc.CallOption) (*UpdatePermissionResp, error) {
	client := sysClient.NewPermissionRpcClient(m.cli.Conn())
	return client.PermissionUpdate(ctx, in, opts...)
}

func (m *defaultPermissionRpc) PermissionDelete(ctx context.Context, in *DeletePermissionReq, opts ...grpc.CallOption) (*DeletePermissionResp, error) {
	client := sysClient.NewPermissionRpcClient(m.cli.Conn())
	return client.PermissionDelete(ctx, in, opts...)
}
