// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"storm-server/app/sys/cmd/rpc/internal/logic/apprpc"
	"storm-server/app/sys/cmd/rpc/internal/svc"
	"storm-server/app/sys/cmd/rpc/sysClient"
)

type AppRpcServer struct {
	svcCtx *svc.ServiceContext
	sysClient.UnimplementedAppRpcServer
}

func NewAppRpcServer(svcCtx *svc.ServiceContext) *AppRpcServer {
	return &AppRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *AppRpcServer) AppAdd(ctx context.Context, in *sysClient.AddAppReq) (*sysClient.AddAppResp, error) {
	l := apprpclogic.NewAppAddLogic(ctx, s.svcCtx)
	return l.AppAdd(in)
}

func (s *AppRpcServer) AppInfo(ctx context.Context, in *sysClient.AppInfoReq) (*sysClient.AppInfoResp, error) {
	l := apprpclogic.NewAppInfoLogic(ctx, s.svcCtx)
	return l.AppInfo(in)
}

func (s *AppRpcServer) AppList(ctx context.Context, in *sysClient.ListAppReq) (*sysClient.ListAppResp, error) {
	l := apprpclogic.NewAppListLogic(ctx, s.svcCtx)
	return l.AppList(in)
}

func (s *AppRpcServer) AppUpdate(ctx context.Context, in *sysClient.UpdateAppReq) (*sysClient.UpdateAppResp, error) {
	l := apprpclogic.NewAppUpdateLogic(ctx, s.svcCtx)
	return l.AppUpdate(in)
}

func (s *AppRpcServer) AppDelete(ctx context.Context, in *sysClient.DeleteAppReq) (*sysClient.DeleteAppResp, error) {
	l := apprpclogic.NewAppDeleteLogic(ctx, s.svcCtx)
	return l.AppDelete(in)
}
